@startuml

class Lampe {
    - nom : String
    - allume : boolean
    + Lampe(String)
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Hifi {
    - son : int
    + allumer()
    + eteindre()
    + toString() : String
}

class Telecommande {
    + Telecommande()
    + ajouter(Appareil)
    + activer(int)
    + desactiver(int)
    + activerTout()
    + toString() : String
}

class Television {
    - allume : boolean
    + allumer()
    + eteindre()
    + toString() : String
}

interface Appareil{
    + allumer()
    + eteindre()
    + toString() : String
}

class LampeAdaptateur{
    + allumer()
    + eteindre()
    + isAllumer() : boolean
    + toString() : String
}

class HifiAdaptateur{
    + allumer()
    + eteindre()
    + toString() : String
}

class TVAdaptateur{
    + allumer()
    + eteindre()
    + toString() : String
}
Telecommande -right-> "*" Appareil : - devices

LampeAdaptateur .up.|> Appareil
HifiAdaptateur .up.|> Appareil
TVAdaptateur .up.|> Appareil


LampeAdaptateur -down-> "1" Lampe :  - lampe
HifiAdaptateur -down-> "1" Hifi : - hifi
TVAdaptateur -down-> "1" Television : - television




@enduml