@startuml

class Lampe {
    - nom : String
    - allume : boolean
    + Lampe(String)
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Hifi {
    - son : int
    + allumer()
    + eteindre()
    + toString() : String
}

class Telecommande {
    + Telecommande()
    + ajouter(Object)
    + activer(int)
    + desactiver(int)
    + activerTout()
    + toString() : String
}

class Television {
    - allume : boolean
    + allumer()
    + eteindre()
    + toString() : String
}

class Object{
}
Lampe <|-- Object
Hifi <|-- Object
Television <|-- Object
Telecommande <|-- Object 
Object "*" <-- Telecommande : -devices
@enduml