@startuml

class Lampe {
    - nom : String
    - allume : boolean
    + Lampe(String)
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Hifi {
    - son : int
    + allumer()
    + eteindre()
    + toString() : String
}

class Telecommande {
    + Telecommande()
    + ajouter(Appareil)
    + activer(int)
    + desactiver(int)
    + activerTout()
    + toString() : String
}

class Television {
    - allume : boolean
    + allumer()
    + eteindre()
    + toString() : String
}

interface Appareil{
    + allumer()
    + eteindre()
    + isAllumer() : boolean
    + toString : String
}

class LampeAdaptateur{
    + allumer()
    + eteindre()
    + isAllumer() : boolean
    + toString() : String
}

class HifiAdaptateur{
    + allumer()
    + eteindre()
    + isAllumer() : boolean
    + toString() : String
}

class TVAdaptateur{
    + allumer()
    + eteindre()
    + isAllumer() : boolean
    + toString() : String
}

Appareil <|.. LampeAdaptateur
Appareil <|.. HifiAdaptateur
Appareil <|.. TVAdaptateur

LampeAdaptateur --> "1" Lampe :  - lampe
HifiAdaptateur --> "1" Hifi : - hifi
TVAdaptateur --> "1" Television : - television


Telecommande --> "*" Appareil : - devices

@enduml