@startuml

class Lampe {
    - nom : String
    - allume : boolean
    + Lampe(String nom)
    + allumerLampe()
    + eteindreLampe()
    + isAllumeLampe() : boolean
    + toString() : String
}

class Hifi {
    - son : int
    + allumerHifi()
    + eteindreHifi()
    + toString() : String
}

class Telecommande {
    + Telecommande()
    + ajouter(Controllable device)
    + activer(int indexControllable)
    + desactiver(int indexControllable)
    + activerTout()
    + toString() : String
}

class Main {
    + main (String) {static}
    + lancerMenu (Telecommande) {static}
    + ajouter4Lampes (Telecommande) {static}
}

Telecommande --> "*" Lampe : - lampes
Telecommande -> "*" Hifi : - hifi

@enduml