@startuml

interface Controllable {
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Lampe {
    - nom : String
    - allume : boolean
    + Lampe(String nom)
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Hifi {
    - son : int
    + allumer()
    + eteindre()
    + isAllume() : boolean
    + toString() : String
}

class Telecommande {
    + Telecommande()
    + ajouter(Controllable device)
    + activer(int indexControllable)
    + desactiver(int indexControllable)
    + activerTout()
    + toString() : String
}



class Main {
    + main (String) {static}
    + lancerMenu (Telecommande) {static}
    + ajouter4Lampes (Telecommande) {static}
}

Telecommande -> "*" Controllable : - devices

Lampe ..|> Controllable
Hifi ..|> Controllable


@enduml